services:
  - type: web
    name: letgonow-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      npm install
      npm install -g @nestjs/cli
      export PATH=$PATH:$(npm config get prefix)/bin
      tsc -p tsconfig.build.json
      ls -la dist/
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NODE_OPTIONS
        value: "--dns-result-order=ipv4first --no-warnings --max-old-space-size=512"
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
      - key: UV_THREADPOOL_SIZE
        value: "4"
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: PGSSLMODE
        value: "require"
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 