services:
  - type: web
    name: letgonow-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      npm install
      npm install -g @nestjs/cli
      export PATH=$PATH:$(npm config get prefix)/bin
      ./node_modules/.bin/nest build
      ls -la dist/
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 